spring.application.name=aquatrack

spring.profiles.active=local

# logging.level.org.springframework.security=DEBUG

google.client.id=620188598406-jhh7ne0ae2nk9n52oq3sq1hkhqh4n9bk.apps.googleusercontent.com

